# dockerfile for the ML class at TH-Rosenheim
# for the summer term 2026
#
# (c) Prof. Dr. Markus Breunig
#
FROM --platform=$BUILDPLATFORM quay.io/jupyter/tensorflow-notebook:2026-02-09

RUN pip install xgboost==3.1.1
RUN pip install lightgbm==4.6.0
RUN pip install category_encoders==2.8.1