# dockerfile for the Data Science class at TH-Rosenheim
# for the winter term 2026/27
#
# (c) Prof. Dr. Markus Breunig
#
FROM --platform=$BUILDPLATFORM quay.io/jupyter/scipy-notebook:2026-08-03

RUN pip install xgboost==3.4.0
RUN pip install lightgbm==4.7.0
RUN pip install category_encoders==2.10.0
RUN pip install imbalanced-learn==0.14.2